In [1]:
# importing libraries 

import numpy as np
import pandas as pd

# Make Simulated Data For Classification ::

In [2]:
# Preliminaries

from sklearn.datasets import make_classification
import pandas as pd

## Create Simulated Data

# Create a simulated feature matrix and output vector with 5 samples,
features, output = make_classification(n_samples = 5,
                                       
                                       # ten features
                                       n_features = 5,
                                       
                                       # three features that actually predict the output's classes
                                       n_informative = 3,
                                       
                                       # two features that are random and unrelated to the output's classes
                                       n_redundant = 2,
                                       
                                       # three output classes
                                       n_classes = 3,
                                      
                                       # with 20% of observations in the first class, 30% in the second class,
                                       # and 50% in the third class. ('None' makes balanced classes)
                                       weights = [.2, .3, .5])

In [3]:
pd.DataFrame(features)

0         1         2         3         4
0  1.626864 -0.237654 -0.685350  0.017369 -1.550764
1 -1.788618  0.458399 -1.662179  0.303842  1.513819
2  1.042411 -0.017902 -0.998481  0.147211 -1.053017
3  1.127665  1.784622 -0.833946  1.386609 -1.430284
4  0.435771 -1.383685  0.297798 -0.944579 -0.159198

In [4]:
pd.DataFrame(output)

0
0  2
1  2
2  2
3  1
4  0

# Make Simulated Data For Regression ::

In [5]:
# Preliminaries

import pandas as pd
from sklearn.datasets import make_regression

# Create Simulated Data

# Generate fetures, outputs, and true coefficient of 100 samples,
features, output, coef = make_regression(n_samples = 100,
                                         
                                         # three features
                                         n_features = 3,
                                         
                                         # where only two features are useful,
                                         n_informative = 2,
                                         
                                         # a single target value per observation
                                         n_targets = 1,
                                         
                                         
                                         # 0.0 standard deviation of the guassian noise
                                         noise = 0.0,
                                        
                                         # show the true coefficient used to generated the data
                                         coef = True)

In [6]:
df1 = pd.DataFrame(features, columns = ['feature1', 'feature2', 'feature3'])
df1

feature1  feature2  feature3
0  -0.589106  0.864275  0.217924
1  -0.693572 -1.398249 -1.330951
2  -1.682211  0.317069 -1.093249
3   0.620355  0.135127  1.183621
4   0.045559  0.438247 -0.160311
..       ...       ...       ...
95 -0.483509 -0.269873 -0.424360
96  0.437454  0.378635  0.657679
97  0.185463 -0.464731  0.347648
98 -0.399476  0.964912  0.367310
99 -0.745953 -0.548765 -0.607582

[100 rows x 3 columns]

In [7]:
df2 = pd.DataFrame(output, columns = ["Output"])
df2

Output
0   -45.120857
1  -100.866146
2  -180.438188
3    90.012889
4    -0.824989
..         ...
95  -55.174565
96   58.151732
97   26.723678
98  -23.994307
99  -83.705827

[100 rows x 1 columns]

In [8]:
df3 = pd.DataFrame(coef, columns = ['Coefficients'])
df3

Coefficients
0     87.717361
1      0.000000
2     30.074621

In [9]:
# Concatenating all three df into one

df = pd.concat([df1, df2, df3], axis = 1)
df

feature1  feature2  feature3      Output  Coefficients
0  -0.589106  0.864275  0.217924  -45.120857     87.717361
1  -0.693572 -1.398249 -1.330951 -100.866146      0.000000
2  -1.682211  0.317069 -1.093249 -180.438188     30.074621
3   0.620355  0.135127  1.183621   90.012889           NaN
4   0.045559  0.438247 -0.160311   -0.824989           NaN
..       ...       ...       ...         ...           ...
95 -0.483509 -0.269873 -0.424360  -55.174565           NaN
96  0.437454  0.378635  0.657679   58.151732           NaN
97  0.185463 -0.464731  0.347648   26.723678           NaN
98 -0.399476  0.964912  0.367310  -23.994307           NaN
99 -0.745953 -0.548765 -0.607582  -83.705827           NaN

[100 rows x 5 columns]

# Calculate The Average, Variance, And Standard Deviation :: 

In [10]:
# Defining an array

array = np.array([[1,2,3],
                 [3,4,5],
                 [6,7,8],
                [9,10,11]])
array

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
round(np.mean(array), 3),  round(np.var(array), 3),  round(np.std(array), 3)

(5.75, 9.854, 3.139)

# Getting The Diagonal Of A Matrix :: 

In [12]:
# Create matrix

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return diagonal elements
val1 = matrix.diagonal()

#Calculate The Trace

# Calculate the tracre of the matrix
val2 = matrix.diagonal().sum()

val1, val2

(array([1, 5, 9]), 15)

# Flatten A Matrix :: 

In [13]:
# Create matrix

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flatten matrix

matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Find The Maximum And Minimum :: 

In [14]:
np.min(matrix)

1

In [15]:
# Find the maximum element in each row
np.max(matrix, axis=0)

array([7, 8, 9])

In [16]:
# Find the maximum element in each column
np.max(matrix, axis=1)

array([3, 6, 9])

# Calculate Dot Product Of Two Vectors ::

In [17]:
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
np.dot(vector_a, vector_b)

32

In [18]:
# Calculate dot product
vector_a @ vector_b

32

# Adding And Subtracting Matrices :: 

In [19]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [20]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

# Convert Pandas Categorical Data For Scikit-Learn :: 

In [21]:
# Import required packages
from sklearn import preprocessing
import pandas as pd


# Create DataFrame
raw_data = {'patient': [1, 1, 1, 2, 2],
        'obs': [1, 2, 3, 1, 2],
        'treatment': [0, 1, 0, 1, 0],
        'score': ['strong', 'weak', 'normal', 'weak', 'strong']}

df = pd.DataFrame(raw_data, columns = ['patient', 'obs', 'treatment', 'score'])
df

patient  obs  treatment   score
0        1    1          0  strong
1        1    2          1    weak
2        1    3          0  normal
3        2    1          1    weak
4        2    2          0  strong

In [22]:
from sklearn import preprocessing

# Fit The Label Encoder

# Create a label (category) encoder object
le = preprocessing.LabelEncoder()

# Fit the encoder to the pandas column
le.fit(df['score'])


LabelEncoder()

In [23]:
# View The Labels

# View the labels (if you want)
list(le.classes_)

['normal', 'strong', 'weak']

# Transform Categories Into Integers

In [24]:
# Apply the fitted encoder to the pandas column

le.transform(df['score']) 

array([1, 2, 0, 2, 1])

# Transform Integers Into Categories

In [25]:
# Convert some integers into their category names

list(le.inverse_transform([2, 2, 1, 0]))

['weak', 'weak', 'strong', 'normal']

# Delete Observations With Missing Values

In [26]:
# Create feature matrix

X = np.array([[1.1, 11.1], 
              [np.nan, 22.2], 
              [3.3, 33.3], 
              [4.4, np.nan], 
              [np.nan, 55]])


# Remove observations with missing values row wise with axis = 1
# it deletes entire row if it has any NaN value

X[~np.isnan(X).any(axis=1)]

array([[ 1.1, 11.1],
       [ 3.3, 33.3]])

In [27]:
# Drop Missing Values Using pandas

# Load data as a data frame
df = pd.DataFrame(X, columns=['feature_1', 'feature_2'])

df

feature_1  feature_2
0        1.1       11.1
1        NaN       22.2
2        3.3       33.3
3        4.4        NaN
4        NaN       55.0

In [28]:
# Remove observations with missing values

df.dropna()

feature_1  feature_2
0        1.1       11.1
2        3.3       33.3

# Imputing Missing Class Labels

In [29]:
# Load libraries
import numpy as np


# Create feature matrix with categorical feature
X = np.array([[0, 2.10, 1.45], 
              [1, 1.18, 1.33], 
              [0, 1.22, 1.27],
              [0, -0.21, -1.19],
              [np.nan, 0.87, 1.31],
              [np.nan, -0.67, -0.22]])

df = pd.DataFrame(X, columns = ['A', 'B', 'C'])
df

A     B     C
0  0.0  2.10  1.45
1  1.0  1.18  1.33
2  0.0  1.22  1.27
3  0.0 -0.21 -1.19
4  NaN  0.87  1.31
5  NaN -0.67 -0.22

In [30]:
from sklearn.impute import SimpleImputer

# Create Imputer object
imputer = SimpleImputer(missing_values = np.nan, strategy='most_frequent')

# Fill missing values with most frequent class
imputer.fit_transform(X)

array([[ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 0.  , -0.21, -1.19],
       [ 0.  ,  0.87,  1.31],
       [ 0.  , -0.67, -0.22]])

In [31]:
# Create Imputer object
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')

# Fill missing values with mean value of that particular column
imputer.fit_transform(X)

array([[ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 0.  , -0.21, -1.19],
       [ 0.25,  0.87,  1.31],
       [ 0.25, -0.67, -0.22]])

In [32]:
# Create Imputer object
imputer = SimpleImputer(missing_values = np.nan, strategy='median')

# Fill missing values with median value of that particular column
imputer.fit_transform(X)

array([[ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 0.  , -0.21, -1.19],
       [ 0.  ,  0.87,  1.31],
       [ 0.  , -0.67, -0.22]])

In [33]:
# The SimpleImputer class also supports categorical data represented as string values or pandas categoricals when using the 'most_frequent' or 'constant' strategy:

df = pd.DataFrame([["a", "x"],
                   [np.nan, "y"],
                   ["a", np.nan],
                  ["b", "y"]], dtype="category")

imp = SimpleImputer(missing_values = np.nan, strategy="most_frequent")

print(imp.fit_transform(df))

[['a' 'x']
 ['a' 'y']
 ['a' 'y']
 ['b' 'y']]


# Imputing Missing Class Labels Using k-Nearest Neighbors ::

In [34]:
# Load libraries
import numpy as np
from sklearn.impute import KNNImputer

nan = np.nan

# Create feature matrix with categorical feature
X = np.array([[0, 2.10, 1.45], 
              [nan, 1.18, nan], 
              [0, nan, 1.27],
              [1, -0.21, -1.19]])


# Train KNN Imputer and fitting the values
clf = KNNImputer(n_neighbors = 3, weights = 'distance')
clf.fit_transform(X)

array([[ 0.        ,  2.1       ,  1.45      ],
       [ 0.3982684 ,  1.18      ,  0.39857143],
       [ 0.        ,  1.95335841,  1.27      ],
       [ 1.        , -0.21      , -1.19      ]])

In [35]:
# Load libraries

import numpy as np
from sklearn.neighbors import KNeighborsClassifier

# Create feature matrix with categorical feature
X = np.array([[0, 2.10, 1.45], 
              [1, 1.18, 1.33], 
              [0, 1.22, 1.27],
              [1, -0.21, -1.19]])


# Create feature matrix with missing values in the categorical feature
X_with_nan = np.array([[np.nan, 0.87, 1.31], 
                       [np.nan, -0.67, -0.22]])

In [36]:
# Train KNN learner

clf = KNeighborsClassifier(n_neighbors = 3, weights = 'distance')
trained_model = clf.fit(X[:,1:], X[:,0])
trained_model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='distance')

In [37]:
from sklearn.impute import MissingIndicator

nan = np.nan
array = np.array([[1,2,3],
                 [4,nan, nan],
                 [nan, 5, nan],
                 [6,nan, nan]])

missing_imputer = MissingIndicator(missing_values = np.nan)

mask_val = missing_imputer.fit_transform(array)
mask_val

array([[False, False, False],
       [False,  True,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [38]:
missing_imputer.features_

array([0, 1, 2], dtype=int64)