In [11]:
text = "A him polymath in the true sense, Farhan Akhtar is known as a writer, singer, actor, director and a producer too \
The actor's career trajectory has always been one to look forward to, for the memorable characters he has always given \
and the projects that he has been a part of. Looking his dapper best on the cover of a leading magazine on their latest\
issue, 'Farhantastic' is totally a mood and we look it! The magazine writes, `Understated performances \
insane body transformations or the courage to always speak his mind. What makes Farhan Akhtar a consistent \
favourite amongst the fans?`, and righty so. Donning a beige floral printed day-suit with a casual round neck \
white t-shirt standing amidst lush greens, Farhan looks like a vision on the cover. With every character \
one has always seen Farhan bring insane body transformations, the best examples are Bhaag Milkha Bhaag and his \
upcoming, Toofaan. The actor has also always spoken his mind with his wordplay and they've always struck the right \
chord and stay in our hearts forever. Some of the best examples being Dil Dhadakne Do, Zindagi Na Milegi Dobara. \
With each project, the actors delivers something new and adds the Farhan element to it. For example, in Zindagi Na \
Milegi Dobara we saw his poetic side, Bhaag Milkha Bhaag, his dedication for becoming the perfect reel life 'Milkha'\
was just incredible. The actor's way of portrayals has always been something one looks forward to. Farhan always \
ensures that as an actor, he chooses his projects that he feels connected to instantly and with that attachment, the \
audiences are always able to enjoy his every performance. Farhan's performances, his dedication to give in everything \
to his roles and fearlessness of speaking his mind- hence, a word that describes him best is his own, `Farhantastic`.\
The fans are all excited and looking forward to seeing Farhan next in the sports drama titled 'Toofaan' which has \
already created a great thunder with its poster releases. The film is being produced by Excel Entertainment."

print("Length of the text:: ",len(text))

Length of the text::  2033


In [14]:
import numpy as np
import pandas as pd
import nltk
import spacy
from nltk.corpus import stopwords                                      # for stop words
from nltk.tokenize import word_tokenize                                # for tokenization of text
from nltk.stem.porter import PorterStemmer                             # for Lemmatization
from nltk.stem.snowball import SnowballStemmer                         # for Lemmatization
from nltk.util import ngrams
from nltk.stem import WordNetLemmatizer


In [12]:
# converting the text into token
token = word_tokenize(text)

# defining stopwords

stop_words = nltk.corpus.stopwords.words('english')

new_text = []
for word in token:
    if word not in stop_words:
        new_text.append(word)
print("Length of the text after removing stop words:: ",len(new_text))

Length of the text after removing stop words::  255


In [19]:
# Performing the lemmitization 

lem_wordnet = WordNetLemmatizer()
token_wordnet = [lem_wordnet.lemmatize(word) for word in new_text]
print(token_wordnet)



['A', 'polymath', 'true', 'sense', ',', 'Farhan', 'Akhtar', 'known', 'writer', ',', 'singer', ',', 'actor', ',', 'director', 'producer', 'The', 'actor', "'s", 'career', 'trajectory', 'always', 'one', 'look', 'forward', ',', 'memorable', 'character', 'always', 'given', 'project', 'part', '.', 'Looking', 'dapper', 'best', 'cover', 'leading', 'magazine', 'latestissue', ',', "'Farhantastic", "'", 'totally', 'mood', 'look', '!', 'The', 'magazine', 'writes', ',', '`', 'Understated', 'performance', 'insane', 'body', 'transformation', 'courage', 'always', 'speak', 'mind', '.', 'What', 'make', 'Farhan', 'Akhtar', 'consistent', 'favourite', 'amongst', 'fan', '?', '`', ',', 'righty', '.', 'Donning', 'beige', 'floral', 'printed', 'day-suit', 'casual', 'round', 'neck', 'white', 't-shirt', 'standing', 'amidst', 'lush', 'green', ',', 'Farhan', 'look', 'like', 'vision', 'cover', '.', 'With', 'every', 'character', 'one', 'always', 'seen', 'Farhan', 'bring', 'insane', 'body', 'transformation', ',', 'bes

In [21]:
# Performing the lemmatization using Spacy

lem_spacy = spacy.load('en_core_web_sm', parse = True, tag = True, entity = True)

token_spacy = lem_spacy(str(new_text))
print(token_spacy)

['A', 'polymath', 'true', 'sense', ',', 'Farhan', 'Akhtar', 'known', 'writer', ',', 'singer', ',', 'actor', ',', 'director', 'producer', 'The', 'actor', "'s", 'career', 'trajectory', 'always', 'one', 'look', 'forward', ',', 'memorable', 'characters', 'always', 'given', 'projects', 'part', '.', 'Looking', 'dapper', 'best', 'cover', 'leading', 'magazine', 'latestissue', ',', "'Farhantastic", "'", 'totally', 'mood', 'look', '!', 'The', 'magazine', 'writes', ',', '`', 'Understated', 'performances', 'insane', 'body', 'transformations', 'courage', 'always', 'speak', 'mind', '.', 'What', 'makes', 'Farhan', 'Akhtar', 'consistent', 'favourite', 'amongst', 'fans', '?', '`', ',', 'righty', '.', 'Donning', 'beige', 'floral', 'printed', 'day-suit', 'casual', 'round', 'neck', 'white', 't-shirt', 'standing', 'amidst', 'lush', 'greens', ',', 'Farhan', 'looks', 'like', 'vision', 'cover', '.', 'With', 'every', 'character', 'one', 'always', 'seen', 'Farhan', 'bring', 'insane', 'body', 'transformations', 

In [24]:
# Performing Stemming on the text

stem_porter = PorterStemmer()
stem_snowball = SnowballStemmer('english')
token_porter = [stem_porter.stem(word) for word in new_text]
token_snowball = [stem_snowball.stem(word) for word in new_text]


['a', 'polymath', 'true', 'sens', ',', 'farhan', 'akhtar', 'known', 'writer', ',', 'singer', ',', 'actor', ',', 'director', 'produc', 'the', 'actor', "'s", 'career', 'trajectori', 'alway', 'one', 'look', 'forward', ',', 'memor', 'charact', 'alway', 'given', 'project', 'part', '.', 'look', 'dapper', 'best', 'cover', 'lead', 'magazin', 'latestissu', ',', 'farhantast', "'", 'total', 'mood', 'look', '!', 'the', 'magazin', 'write', ',', '`', 'underst', 'perform', 'insan', 'bodi', 'transform', 'courag', 'alway', 'speak', 'mind', '.', 'what', 'make', 'farhan', 'akhtar', 'consist', 'favourit', 'amongst', 'fan', '?', '`', ',', 'righti', '.', 'don', 'beig', 'floral', 'print', 'day-suit', 'casual', 'round', 'neck', 'white', 't-shirt', 'stand', 'amidst', 'lush', 'green', ',', 'farhan', 'look', 'like', 'vision', 'cover', '.', 'with', 'everi', 'charact', 'one', 'alway', 'seen', 'farhan', 'bring', 'insan', 'bodi', 'transform', ',', 'best', 'exampl', 'bhaag', 'milkha', 'bhaag', 'upcom', ',', 'toofaan'

In [27]:
# Converting the data into matrix form

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
text_vec = vectorizer.fit_transform(new_text)

#print(vectorizer.vocabulary_)            # Changing text into a dictionary
print(text_vec.todense())                 # Chacnging text into a matrix


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [34]:
# Building our vocabulary

set_of_words = set()
string = str(' '.join(new_text))               #Changing list into a string
for words in string.split():                   # Splitting the string to iterate over it
    set_of_words.add(words)
vocab = list(set_of_words)
print(vocab)

['wordplay', 'example', 'Na', 'righty', 'look', 'characters', 'The', 'element', ',', 'stay', 'already', 'character', 'standing', 'performances', 'Bhaag', 'vision', 'life', 'bring', 'singer', 'one', 'magazine', "'", 'seeing', 'give', 'dapper', 'Entertainment', 'writer', 'A', 'mood', 'Farhan', '.', 'Understated', 'Dobara', 'fearlessness', 'insane', 'trajectory', '!', 'struck', 'performance', 'producer', 'perfect', 'every', 'new', 'Some', 'printed', 'lush', 'amidst', 'Toofaan', 'actor', 'For', 'side', 'right', 'speaking', 'saw', 'part', 'everything', 'projects', 'Zindagi', 'able', 'upcoming', 'describes', 'excited', 'given', 'looks', 'known', 'examples', "'Farhantastic", 'poetic', 'Looking', 'beige', 'day-suit', 'adds', 'produced', 'With', 'transformations', 'amongst', 'neck', 'like', 'chord', 'becoming', 'project', 'Donning', 'forward', 'instantly', 'way', 'true', 'white', 'also', 'What', '.The', 'something', 'sports', 'round', 'polymath', 'Milegi', 'hearts', 'connected', 'portrayals', '

In [36]:
# Fetching the position/index of each token in the vocabulary

position = {}

for pos, word in enumerate(vocab):
    position[pos] = word
print(position)

{0: 'wordplay', 1: 'example', 2: 'Na', 3: 'righty', 4: 'look', 5: 'characters', 6: 'The', 7: 'element', 8: ',', 9: 'stay', 10: 'already', 11: 'character', 12: 'standing', 13: 'performances', 14: 'Bhaag', 15: 'vision', 16: 'life', 17: 'bring', 18: 'singer', 19: 'one', 20: 'magazine', 21: "'", 22: 'seeing', 23: 'give', 24: 'dapper', 25: 'Entertainment', 26: 'writer', 27: 'A', 28: 'mood', 29: 'Farhan', 30: '.', 31: 'Understated', 32: 'Dobara', 33: 'fearlessness', 34: 'insane', 35: 'trajectory', 36: '!', 37: 'struck', 38: 'performance', 39: 'producer', 40: 'perfect', 41: 'every', 42: 'new', 43: 'Some', 44: 'printed', 45: 'lush', 46: 'amidst', 47: 'Toofaan', 48: 'actor', 49: 'For', 50: 'side', 51: 'right', 52: 'speaking', 53: 'saw', 54: 'part', 55: 'everything', 56: 'projects', 57: 'Zindagi', 58: 'able', 59: 'upcoming', 60: 'describes', 61: 'excited', 62: 'given', 63: 'looks', 64: 'known', 65: 'examples', 66: "'Farhantastic", 67: 'poetic', 68: 'Looking', 69: 'beige', 70: 'day-suit', 71: 'ad

In [38]:
bow_matrix = np.zeros((len(new_text), len(vocab)))
bow_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [42]:
# Getting the sentiment of the text

from textblob import TextBlob

TextBlob(string).sentiment

Sentiment(polarity=0.297002997002997, subjectivity=0.5845612720612721)

In [44]:
TextBlob(data).sentiment

Sentiment(polarity=0.08821021571021574, subjectivity=0.4667772351105685)

In [49]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyser = SentimentIntensityAnalyzer()
print(analyser.polarity_scores(text))
print(analyser.polarity_scores(' '.join(new_text)))

{'neg': 0.019, 'neu': 0.825, 'pos': 0.155, 'compound': 0.9942}
{'neg': 0.025, 'neu': 0.778, 'pos': 0.198, 'compound': 0.9942}


In [50]:
print(vectorizer.get_feature_names())

['able', 'actor', 'actors', 'adds', 'akhtar', 'already', 'also', 'always', 'amidst', 'amongst', 'attachment', 'audiences', 'becoming', 'beige', 'best', 'bhaag', 'body', 'bring', 'career', 'casual', 'character', 'characters', 'chooses', 'chord', 'connected', 'consistent', 'courage', 'cover', 'created', 'dapper', 'day', 'dedication', 'delivers', 'describes', 'dhadakne', 'dil', 'director', 'do', 'dobara', 'donning', 'drama', 'element', 'enjoy', 'ensures', 'entertainment', 'every', 'everything', 'example', 'examples', 'excel', 'excited', 'fans', 'farhan', 'farhantastic', 'favourite', 'fearlessness', 'feels', 'film', 'floral', 'for', 'forever', 'forward', 'give', 'given', 'great', 'greens', 'hearts', 'hence', 'incredible', 'insane', 'instantly', 'known', 'latestissue', 'leading', 'life', 'like', 'look', 'looking', 'looks', 'lush', 'magazine', 'makes', 'memorable', 'milegi', 'milkha', 'mind', 'mood', 'na', 'neck', 'new', 'next', 'one', 'part', 'perfect', 'performance', 'performances', 'poeti