NumPy program to test whether none of the elements of a given array is zero.

In [5]:
import numpy as np
a = np.array([1,2,3,4,5])
print("Array is:: ", a)
print("\nCheck whether any element is zero.")
print(np.all(a))

b = np.array([0,1,0,2,4])
print("\nArray is:: ", b)
print("\n Check whether any elemnt is zero.")
print(np.all(b))


Array is::  [1 2 3 4 5]

Check whether any element is zero.
True

Array is::  [0 1 0 2 4]

 Check whether any elemnt is zero.
False


NumPy program to test whether any of the elements of a given array is non-zero.


In [7]:
a = np.array([1,2,3,4,5])
print('\nArray is:: ', a)
print("Test if given array has any non-zero element.")
print(np.any(a))

b = np.array([6,7,8,9,0])
print('\nArray is:: ', b)
print("Test if given array has any non-zero element.")
print(np.any(b))

c = np.array([0,0,0,0,0])
print('\nArray is::', c)
print("Test if given array has any non-zero element.")
print(np.any(c))



Array is::  [1 2 3 4 5]
Test if given array has any non-zero element.
True

Array is::  [6 7 8 9 0]
Test if given array has any non-zero element.
True

Array is:: [0 0 0 0 0]
Test if given array has any non-zero element.
False


In [ ]:
NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [9]:
a = np.array([1,2, np.nan, np.inf])         ## nan : Not a number  & inf = Infinity
print('\nArray is:: ', a)
print("\nTest for given array for finiteness. (not infinity or not a Number)")
print(np.isfinite(a))


Array is::  [ 1.  2. nan inf]

Test for given array for finiteness. (not infinity or not a Number)
[ True  True False False]


 NumPy program to test element-wise for positive or negative infinity.

In [10]:
a = np.array([1,2, np.nan, np.inf])         ## nan : Not a number  & inf = Infinity
print('\nArray is:: ', a)
print("\nTest for given array for postive or negative infinity elements.")
print(np.isinf(a))


Array is::  [ 1.  2. nan inf]

Test for given array for postive or negative elements.
[False False False  True]


NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [12]:
a = np.array([1, 2, 3 + 2j, 4 + 5j, 4.5, 2.1])
print('\n Original array is:: ')
print(a)
print("\nElement wise Test to Check for real number: ")
print(np.isreal(a))
print("\nElement wise test to check for complex number.")
print(np.iscomplex(a))
print("\nElement wise test to check for Scalar type.")
print(np.isscalar(a))



 Original array is:: 	
[1. +0.j 2. +0.j 3. +2.j 4. +5.j 4.5+0.j 2.1+0.j]

Element wise Test to Check for real number: 
[ True  True False False  True  True]

Element wise test to check for complex number.
[False False  True  True False False]

Element wise test to check for Scalar type.
False


NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [18]:
import numpy as np

x = np.array([1,2,3])   ## both Arrays should be of equal size
y = np.array([3,4,5])

print('\nFirst Array is:: ',x)
print("\nSecond Array is:: ",y)

print("\nTest for Comparison - Greater.")
print(np.greater(x, y))                             ##Greater check
print("\nTest of comparison - Greater or equal")
print(np.greater_equal(x,y))                         ## Greater or equal check
print("\nTest for comparison - Less")
print(np.less(x,y))                                  ## Less check
print("\nTest for comparison - Less equal")
print(np.less_equal(x,y))                            ## Less equal
print("\nTest for comparison - Equal")
print(np.equal(x,y))                                 ## Equal check
print("\nComparison - Equal within tolerance")
print(np.allclose(x,y))                              



First Array is::  [1 2 3]

Second Array is::  [3 4 5]

Test for Comparison - Greater.
[False False False]

Test of comparison - Greater or equal
[False False False]

Test for comparison - Less
[ True  True  True]

Test for comparison - Less equal
[ True  True  True]

Test for comparison - Equal
[False False False]

Comparison - Equal within tolerance
False


NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [7]:
import numpy as np

a = np.arange(10)

print("\nOriginal Array: ", a)
print("\nArray of all ones:: ")

b = np.ones(10)
print(b)

print("\nArray of all zeros: ")
c = np.zeros(10)
print(c)

print("\nArray of all 5's")
d = b * 5
print(d)

print(f"""\n
Size of all arrays:
Array: '{a}' : {np.shape(a)}
Array: '{b}' : {np.shape(b)}
Array: '{c}' : {np.shape(c)}
Array: '{d}' : {np.shape(d)}
""")


Original Array:  [0 1 2 3 4 5 6 7 8 9]

Array of all ones:: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Array of all zeros: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Array of all 5's
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Size of all arrays:
Array: '[0 1 2 3 4 5 6 7 8 9]' : (10,)
Array: '[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]' : (10,)
Array: '[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]' : (10,)
Array: '[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]' : (10,)



NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [10]:
import numpy as np

a = np.identity(3)
print("\n3x3 Identity matrix:: ")
print(a)


3x3 Identity matrix:: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


NumPy program to create an array of all the even integers from 30 to 70.

In [11]:
a = np.arange(30,71,2)
print('\nMAtrix is::')
print(a)


MAtrix is::
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


NumPy program to generate a random number between 0 and 1

In [13]:
a = np.random.normal(0,1,1)   ##(Start, end, items reqd)
print("\nRandom Number between 0 and 1::")
print(a)



Random Number between 0 and 1::
[0.05894579]


NumPy program to generate 15 random number between 0 and 10

In [14]:
a = np.random.normal(0,1,15)
print("\n15 Random numbers between 0 and 1 in a matrix:")
print(a)


15 Random numbers between 0 and 1 in a matrix:
[ 0.59301004 -0.51319765  1.93312504  0.42240028  1.7565433  -0.95013766
 -0.61098213 -1.01157776 -1.03267567  0.82791808  0.98472622  1.00753332
 -0.49140046  0.16645557  1.1936436 ]


NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.

In [15]:
a = np.arange(15,55)
print("\nOriginal Matrix::", a)
print("\nmatrix after removing first and last element: ", a[1:-1])



Original Matrix:: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]

matrix after removing first and last element:  [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


NumPy program to create a 3X4 array using and iterate over it.

In [20]:
a = np.arange(12,24).reshape(3,4)
print("\nFinal matrix :: \n", a)   

## Iterate over the matrix

print("\nIndividual element of the matrix")
for i in np.nditer(a):
    print(i, end = " ")


Final matrix :: 
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Individual element of the matrix
12 13 14 15 16 17 18 19 20 21 22 23 

NumPy program to create a vector of length 10 with values ​​evenly distributed between 5 and 50.

In [2]:
import numpy as np

a = np.arange(5,51,5)
print("\n Vector of length 10:: ")
print(a)


 Vector of length 10:: 
[ 5 10 15 20 25 30 35 40 45 50]


NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [8]:
a = np.ones(100).reshape(10,10)
print("\nOriginal Array;; \n", a)

a[1:-1, 1:-1] = 0

print("\n Modified array:: \n", a) 


Original Array;; 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 Modified array:: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


NumPy program to create a 3x4 matrix filled with values ​​from 10 to 21.

In [10]:
a= np.arange(10,22).reshape(3,4)

print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


NumPy program to multiply the values ​​of two given vectors

In [12]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print("\nOriginal first array:: \n", a)
print("\nOriginal second array:: \n", b)

c = a * b

print("\nFinal array after multiplication :: \n", c)


Original first array:: 
 [[1 2]
 [3 4]]

Original second array:: 
 [[5 6]
 [7 8]]

Final array after multiplication :: 
 [[ 5 12]
 [21 32]]


In [15]:
a = np.random.randint(0,10,5)
print("Vector of length 5 filled with random number between 0 & 10")
print("\nFinal Matrix :: \n", a)

Vector of length 5 filled with random number between 0 & 10

Final Matrix :: 
 [5 1 6 3 9]


NumPy program to create a vector with values ​​from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [21]:
x = np.arange(21)
print("\nOriginal Matrix :: \n", x)

## Multiplying each element from 9-15 with -1

x[(x >= 9) & (x <= 15)] *= -1

print("\nFinal matrix :: ", x)




Original Matrix :: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Final matrix ::  [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


NumPy program to add a vector to each row of a given matrix.

In [35]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print("\nOriginal Matrix :: \n", a)

b = np.array([1,2,3])
print("\nSecond matrix to be added:: \n", b)

c = np.empty_like(a)

for i in range(4):
    c[i, :] = a[i, :] + b
    print("\nFinal Matrix after addition ::  \n", c)


Original Matrix :: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Second matrix to be added:: 
 [1 2 3]

Final Matrix after addition ::  
 [[ 2  4  6]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Final Matrix after addition ::  
 [[ 2  4  6]
 [ 5  7  9]
 [ 7  8  9]
 [10 11 12]]

Final Matrix after addition ::  
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [10 11 12]]

Final Matrix after addition ::  
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


Enter four value to enter: 


 4 5 6 7


22
