In [7]:
import numpy as np

array = np.array([1,2,3,4,5])
x = (np.arange(10))
y = (np.arange(1,20,2))
z = (np.arange(1,10,1))
print(x)
print(y)
print(z)
print(array)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


In [9]:
a = np.array([1,2,3,4,5,6])
b = np.array([[1,2,3], [4,5,6]])
c = np.array([[[1,2,3], [4,5,6]]])
print(a)
print(b)
print(c)
print(len(a))
print(len(b))
print(len(c))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]]
6
2
1


In [10]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(c)
print(len(c))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
2


In [19]:
a = np.zeros(3)
b = np.zeros((3,3))
c = np.zeros(((3,3,3)))

print('c\n',c)


c
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [20]:
a = np.eye(2, 3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]]


In [21]:
a = np.diag([1,2,3,4,5,6])
print(a)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [26]:
a = np.random.randn(1,10)
b = np.random.randn(1,10,5)
c = np.random.randint(0,10)
d = np.random.randint(1,10,3)
print(a)
print(b)


[[-0.04165088 -0.0574939  -0.22901959  0.84516211 -1.556687    1.02108952
   0.92623017  1.36786643 -1.31477099  0.35452984]]
[[[ 1.33504408  0.10122562 -0.05582797 -0.66955817 -0.25863022]
  [ 0.29635116  1.34646802 -1.68710016 -0.73045519  1.67009338]
  [ 0.40277826 -0.12053522  0.60552092  1.51311277 -1.26194437]
  [ 0.75922263 -1.23182085 -0.9318887  -0.91671408 -0.4244257 ]
  [ 1.00280053 -1.72421667  0.66446664 -0.00637328 -0.91491925]
  [-0.42973315  0.55233661  0.41418669  1.21560559 -0.3095134 ]
  [ 1.92771605 -0.15944679 -0.26359642  0.39411456  1.01096469]
  [ 1.53131084  0.29295675 -0.22915436 -0.7636061  -0.22632033]
  [ 1.32130534 -0.55226334 -0.72947792 -0.12352697 -0.18282944]
  [ 0.54319254  0.99215267  0.02693658  0.01385025  0.64659715]]]


In [28]:
a = np.random.randn(3,4)
print(a)

[[ 0.98744576  0.04882627  0.36916423  0.5337304 ]
 [-0.45417532 -0.97250359 -0.67524586  0.95649933]
 [-1.0948138   0.64257053  1.46967154  0.74325759]]


In [30]:
a = np.arange(10)
print('a is', a)
print(a.dtype)

a is [0 1 2 3 4 5 6 7 8 9]
int32


In [31]:
a = np.array([True, False, True])
print('Array a is ', a)
print(a.dtype)

Array a is  [ True False  True]
bool
